"""Adding email table

Revision ID: 06bae9ba0e68
Revises: f74959b9a29d
Create Date: 2020-11-12 18:45:53.561138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06bae9ba0e68'
down_revision = 'f74959b9a29d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.Unicode(), nullable=False),
    sa.Column('body', sa.Unicode(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('send_tries', sa.Integer(), nullable=False),
    sa.Column('next_try', sa.DateTime(), nullable=False),
    sa.Column('sent', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_email_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email')
    # ### end Alembic commands ###
