"""Renaming user.username to user.name

Revision ID: 24cdd3c40c92
Revises:
Create Date: 2020-11-06 21:50:31.721180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24cdd3c40c92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column(
        'name', sa.String(length=40), nullable=True))
    op.execute("UPDATE user SET name = username")

    with op.batch_alter_table('user') as batch_op:
        batch_op.create_unique_constraint('uq_user_email', ['email'])
        batch_op.alter_column('name', nullable=False)
        batch_op.drop_column('username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column(
        'username', sa.VARCHAR(length=40), nullable=True))
    op.execute("UPDATE user SET username = name")

    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_constraint('uq_user_email', type_='unique')
        batch_op.alter_column('username', nullable=False)
        batch_op.drop_column('name')
    # ### end Alembic commands ###
