"""Adding alternative user id

Revision ID: 7336d94772b0
Revises: d8757ef5fa27
Create Date: 2020-11-21 13:40:10.745974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7336d94772b0'
down_revision = 'd8757ef5fa27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('login_id', sa.Integer(), nullable=True))
    op.execute("UPDATE user SET login_id = id")

    with op.batch_alter_table('user') as batch_op:
        batch_op.create_unique_constraint(op.f('uq_user_login_id'), ['login_id'])
        batch_op.alter_column('login_id', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_constraint(op.f('uq_user_login_id'), type_='unique')
        batch_op.drop_column('login_id')
    # ### end Alembic commands ###
