"""Adding account delete request date

Revision ID: b21c10beec12
Revises: 7336d94772b0
Create Date: 2020-11-21 18:05:37.555008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b21c10beec12'
down_revision = '7336d94772b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.add_column(sa.Column('delete_request', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_column('delete_request')
    # ### end Alembic commands ###
