"""Fixing delete cascade

Revision ID: c08f199af306
Revises: ee75e898dcfc
Create Date: 2020-11-14 14:37:42.537246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c08f199af306'
down_revision = 'ee75e898dcfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_user') as batch_op:
        batch_op.drop_constraint('fk_role_user_user_id_user', type_='foreignkey')
        batch_op.create_foreign_key(op.f('fk_role_user_user_id_user'), 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_user') as batch_op:
        batch_op.drop_constraint(op.f('fk_role_user_user_id_user'), type_='foreignkey')
        batch_op.create_foreign_key('fk_role_user_user_id_user', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
