"""Adding creation date to user

Revision ID: d8757ef5fa27
Revises: c08f199af306
Create Date: 2020-11-16 19:53:58.819074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8757ef5fa27'
down_revision = 'c08f199af306'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email') as batch_op:
        batch_op.add_column(
            sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.drop_column('creation_date')

    with op.batch_alter_table('user') as batch_op:
        batch_op.add_column(
            sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('email') as batch_op:
        batch_op.add_column(
            sa.Column('creation_date', sa.DATETIME(), nullable=False))
        batch_op.drop_column('created_at')
    # ### end Alembic commands ###
