"""Adding role table

Revision ID: ee75e898dcfc
Revises: 06bae9ba0e68
Create Date: 2020-11-14 13:35:35.548027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee75e898dcfc'
down_revision = '06bae9ba0e68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=40), nullable=False),
                    sa.Column('description', sa.String(
                        length=100), nullable=True),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_role')),
                    sa.UniqueConstraint('name', name=op.f('uq_role_name'))
                    )
    op.create_table('role_user',
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('role_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['role_id'], ['role.id'], name=op.f('fk_role_user_role_id_role')),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['user.id'], name=op.f('fk_role_user_user_id_user'))
                    )

    with op.batch_alter_table('user') as batch_op:
        batch_op.add_column(sa.Column('banned', sa.Boolean(), nullable=False))
        batch_op.add_column(
            sa.Column('confirmed_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('verified')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.add_column(
            sa.Column('verified', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('confirmed_at')
        batch_op.drop_column('banned')

    op.drop_table('role_user')
    op.drop_table('role')
    # ### end Alembic commands ###
