"""Adding slug identifiers to user and post

Revision ID: f74959b9a29d
Revises: 24cdd3c40c92
Create Date: 2020-11-07 15:31:02.320392

"""
from sqlalchemy.orm import Session
from alembic import op
from slugify import slugify
from tfp.site.models.user import User
from tfp.site.models.post import Post
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f74959b9a29d'
down_revision = '24cdd3c40c92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    session = Session(bind=conn)

    op.add_column('post', sa.Column(
        'title_slug', sa.Unicode(), nullable=True))
    op.add_column('user', sa.Column('username', sa.Unicode(), nullable=True))

    users = session.query(User).filter_by(username=None)

    for user in users:
        slug = slugify(user.email.split('@')[0], separator='_')
        username = slug
        count = 1

        while session.query(User).filter_by(username=username).first():
            username = slug + str(count)
            count += 1

        user.username = username

    posts = session.query(Post).filter_by(title_slug=None)

    for post in posts:
        slug = slugify(post.title)
        title_slug = slug
        count = 1

        while session.query(Post).filter_by(title_slug=title_slug).first():
            title_slug = slug + str(count)
            count += 1

        post.title_slug = title_slug

    session.commit()

    with op.batch_alter_table('post') as batch_op:
        batch_op.alter_column('title_slug', nullable=False)
        batch_op.create_unique_constraint('uq_post_title_slug', ['title_slug'])

    with op.batch_alter_table('user') as batch_op:
        batch_op.alter_column('username', nullable=False)
        batch_op.create_unique_constraint('uq_user_username', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_constraint('uq_user_username', type_='unique')
        batch_op.drop_column('username')

    with op.batch_alter_table('post') as batch_op:
        batch_op.drop_constraint('uq_post_title_slug', type_='unique')
        batch_op.drop_column('title_slug')
    # ### end Alembic commands ###
